apiVersion: v1
kind: Service
metadata:
  name: ppu-exporter-mock-service
  namespace: ppu-system
  labels:
    app: ppu-exporter-mock
    component: exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ppu-exporter-mock
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP